
data class FlavorConfig(
    val name: String,
    val displayName: String,
    val packageName: String,
    val audioFileName: String? = null,
    val isPrayerTimesFlavor: Boolean = false,
    val contentFamily: String = "content",
    val monetizationProfile: String = "standard",
    val notificationProfile: String = "default",
    val billingProfile: String = "prepaid_ad_free",
    val themeTokenKey: String = name,
    val capabilityFlags: List<String> = emptyList(),
)

object AppFlavors {
    val all = listOf(
        FlavorConfig(
            name = "amenerrasulu",
            displayName = "Amenerrasulu Sesli",
            packageName = "com.parsfilo.amenerrasulu",
            audioFileName = "amenerrasulu.mp3",
            contentFamily = "content",
            monetizationProfile = "reading",
        ),
        FlavorConfig(
            name = "ayetelkursi",
            displayName = "Ayetel Kursi Sesli",
            packageName = "com.parsfilo.ayetelkursi",
            audioFileName = "ayetelkursi.mp3",
            contentFamily = "content",
            monetizationProfile = "reading",
        ),
        FlavorConfig(
            name = "bereketduasi",
            displayName = "Bereket Duası",
            packageName = "com.parsfilo.bereketduasi",
            audioFileName = "bereketduasi.mp3",
            contentFamily = "content",
        ),
        FlavorConfig(
            name = "esmaulhusna",
            displayName = "Esmaül Hüsna",
            packageName = "com.parsfilo.esmaulhusna",
            audioFileName = "esmaulhusna.mp3",
            contentFamily = "esma",
            capabilityFlags = listOf("play_all_audio"),
        ),
        FlavorConfig(
            name = "fetihsuresi",
            displayName = "Fetih Suresi Sesli",
            packageName = "com.parsfilo.fetihsuresi",
            audioFileName = "fetihsuresi.mp3",
            contentFamily = "content",
        ),
        FlavorConfig(
            name = "insirahsuresi",
            displayName = "İnşirah Sesli",
            packageName = "com.parsfilo.insirahsuresi",
            audioFileName = "insirahsuresi.mp3",
            contentFamily = "content",
        ),
        FlavorConfig(
            name = "ismiazamduasi",
            displayName = "İsmi Azam Sesli",
            packageName = "com.parsfilo.ismiazamduasi",
            audioFileName = "ismiazamduasi.mp3",
            contentFamily = "content",
        ),
        FlavorConfig(
            name = "kenzularsduasi",
            displayName = "Kenzül Arş Sesli",
            packageName = "com.parsfilo.kenzularsduasi",
            audioFileName = "kenzularsduasi.mp3",
            contentFamily = "content",
        ),
        FlavorConfig(
            name = "kible",
            displayName = "Kıble",
            packageName = "com.parsfilo.kible",
            contentFamily = "qibla",
            monetizationProfile = "utility",
        ),
        FlavorConfig(
            name = "kuran_kerim",
            displayName = "Kuran-ı Kerim",
            packageName = "com.parsfilo.kuran_kerim",
            audioFileName = null,
            contentFamily = "quran",
            monetizationProfile = "reading",
        ),
        FlavorConfig(
            name = "mucizedualar",
            displayName = "Mucize Dualar",
            packageName = "com.parsfilo.mucizedualar",
            contentFamily = "miracles",
        ),
        FlavorConfig(
            name = "namazsurelerivedualarsesli",
            displayName = "Namaz Sureleri Sesli",
            packageName = "com.parsfilo.namazsurelerivedualarsesli",
            audioFileName = "fatiha.mp3",
            contentFamily = "prayer_library",
            capabilityFlags = listOf("hide_verse_count", "prefetch_all_audio_first_launch"),
        ),
        FlavorConfig(
            name = "namazvakitleri",
            displayName = "Namaz Vakitleri",
            packageName = "com.parsfilo.namazvakitleri",
            isPrayerTimesFlavor = true,
            contentFamily = "prayer_times",
            monetizationProfile = "prayer_times",
            notificationProfile = "prayer_times",
            capabilityFlags = listOf("prayer_variant_namaz_vakitleri"),
        ),
        FlavorConfig(
            name = "nazarayeti",
            displayName = "Nazar Ayeti",
            packageName = "com.parsfilo.nazarayeti",
            audioFileName = "nazarayeti.mp3",
            contentFamily = "content",
        ),
        FlavorConfig(
            name = "vakiasuresi",
            displayName = "Vakıa Sesli",
            packageName = "com.parsfilo.vakiasuresi",
            audioFileName = "vakiasuresi.mp3",
            contentFamily = "content",
        ),
        FlavorConfig(
            name = "yasinsuresi",
            displayName = "Yasin Sesli",
            packageName = "com.parsfilo.yasinsuresi",
            audioFileName = "yasinsuresi.mp3",
            contentFamily = "content",
            monetizationProfile = "reading",
        ),
        FlavorConfig(
            name = "zikirmatik",
            displayName = "Zikirmatik",
            packageName = "com.parsfilo.zikirmatik",
            contentFamily = "zikir_counter",
            monetizationProfile = "counter",
        ),
    )
}
